CREATE USER 'johnDoe' IDENTIFIED BY 'pass123' DEFAULT ROLE 'Member';
CREATE USER 'employee1' IDENTIFIED BY 'pass123' DEFAULT ROLE 'Employee';
CREATE USER 'adminUser' IDENTIFIED BY 'pass123' DEFAULT ROLE 'Admin';

